### ISSUE TITLE
CRUD App (with Figma)

### ISSUE THREAD

**Issue by Mr-Headrick** [AmazingAJ10/subs5#1]
Finish what you should have done for the midterm.  [Due:  1/8/2024  10:55am]

**Comment by ghost** [comment]
The Update function does not work

**Comment by AmazingAJ10** [comment]
Update is all working 😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁
