### ISSUE TITLE
Create Add button not working with mouse click

### ISSUE THREAD

**Issue by Mr-Headrick** [AmazingAJ10/subs5#6]
This does add a record when keyboard tab to the button and keyboard return key -- however must work as expected with mouse pointer.

**Comment by AmazingAJ10** [comment]
When I click the add button on the Create page, it adds a new subscription, but you have to press the 'x' button to return to the list of subscriptions. I have tried to get it to return to the list after onMouseUp, but it is not working properly so the 'x' button is required. I will show you tomorrow and see if we can figure it out.
